config/routes.rb
Rails.application.routes.draw do

  resources :todos
  root 'welcome#index'
  devise_for :users
  resources :users
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :supervisor
      can :manage, Todo
    elsif user.has_role? :employee
      can :read
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perimission.rb
class Perimission < ApplicationRecord
    
end

app/models/todo.rb
class Todo < ApplicationRecord
    resourcify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one_attached :avatar
  has_and_belongs_to_many :permissions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    rescue_from CanCan::AccessDenied do |exception|
      redirect_to main_app.root_url, notice: exception.message 
    end 

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :avatar])
    end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :desc)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update,:destroy]
  load_and_authorize_resource
  def index
    @users = User.all
  end
 
  def new
    @user = User.new
  end 

  def create
    @user = User.create(user_params)
    if @user.save!
      redirect_to 'users_path', notice: "Successfully created"
    end 
  end 

  def show
    @user.add_role(params[:user][:role])
  end

  def edit
  end 

  def update 
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else 
      render :edit
    end 
  end 

  def destroy
    @user.destroy
    redirect_to 'users_path', notice: 'succesfully deleted'
  end 

  private

  def set_user 
    @user = User.find(params[:id])
  end 
 
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def email(user)
    user.email 
  end 
  def attachment(user)
    image_tag user.avatar.variant(resize:'100x100') if user.avatar.attached?
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="hmenu">
      <%= render "devise/shared/registration_items" %>
      <%= render "devise/shared/login_links" %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.desc %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @todo.desc %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <h4> <%= user.email %> </h4>
    <%= attachment(user)  %>
    <%= user.role %>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
   <%= f.text_field :email, :placeholder => 'email' %>
   <%= f. password_field :password, :placeholder => 'password' %>
   <%= f.password_field :password_confirmation, :placeholder => 'password_confirmation' %>
   <%= f.select(:role, ['employee', 'supervisor','super_admin'], {}) %>
   <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h4><%= @user.email %></h4>
<%= attachment(@user) %>
<h4><%= @user.role %></h4>
<%= check_box_tag "user[role_ids][]", role.id, @user.role_ids.include?(role.id) %>
<%= role.name %><br />
  

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>